version: '3'

services:
  sut:
    build: .
    command: sh -c 'bundle install --with test development && /app/bin/wait-for-postgres.sh rake db:test:prepare && rspec'
    volumes: &volumes
      - .:/app
    environment: &environment
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres@db/lofocats?pool=5&timeout=5000
      # PG* vars used by wait-for-postgres.sh
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=lofocats
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=lofocats
